### ISSUE TITLE
Missing class MultipartRequestHelper

### ISSUE THREAD

**Issue by sergiodesousafilho** [aspnet/AspNetCore.Docs.pt-br#118]
Hello, the class "MultipartRequestHelper" is not implemented or builtin.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Uploads de arquivos no ASP.NET Core](https://docs.microsoft.com/pt-br/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/AspNetCore.Docs.pt-br/blob/live/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @sergiodesousafilho
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Issue moved to [aspnet/AspNetCore.Docs #14796](https://github.com/aspnet/AspNetCore.Docs/issues/14796) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lichasu** [comment]
Hello, @sergiodesousafilho 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/AspNetCore.Docs/issues/14796.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
